### ISSUE TITLE
Broken python example

### ISSUE THREAD

**Issue by the01** [speechcatcher-asr/speechcatcher#6]
When I try to run the [python example](https://github.com/speechcatcher-asr/speechcatcher#use-speechcatcher-in-your-python-code) it fails with

```python
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\flo\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "E:\data\p\projects\env310\lib\site-packages\speechcatcher\speechcatcher.py", line 421, in recognize_segment
    segment_text, prev_lines = batch_recognize_inner_loop(speech_chunk, i, prev_lines,
  File "E:\data\p\projects\env310\lib\site-packages\speechcatcher\speechcatcher.py", line 459, in batch_recognize_inner_loop
    prev_lines = progress_output(nbests[0], prev_lines)
NameError: name 'nbests' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\data\p\projects\src\dev\run_speechcatcher.py", line 214, in <module>
    rec2()
  File "E:\data\p\projects\src\dev\run_speechcatcher.py", line 177, in rec2
    complete_text, paragraphs = speechcatcher.recognize(
  File "E:\data\p\projects\env310\lib\site-packages\speechcatcher\speechcatcher.py", line 332, in recognize
    paragraphs_raw.append(r.result())
  File "C:\Users\flo\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\flo\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
NameError: name 'nbests' is not defined
```

I believe it should be `results[0][0]` in speechcatcher.py line 459

**Comment by bmilde** [comment]
Thanks!
